app/__init__.py
from flask import Flask, render_template
from config import Config
from .api.routes import api
from .site.routes import site
from .authentication.routes import auth
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Book, book_schema, books_schema

api = Blueprint('api',__name__, url_prefix='/api')

@api.route('/books/create', methods = ['POST'])
@token_required
def create_book(current_user_token):
    ISBN = request.json['ISBN']
    author_name = request.json['author_name']
    book_title = request.json['book_title']
    page_count = request.json['page_count']
    book_type = request.json['book_type']
    book = Book(ISBN, author_name, book_title, page_count, book_type)
    db.session.add(book)
    db.session.commit()
    response = book_schema.dump(book)
    return jsonify(response)

@api.route('/books/all', methods = ['GET'])
@token_required
def get_books(current_user_token):
    books = Book.query.filter_by().all()
    response = books_schema.dump(books)
    return jsonify(response)

@api.route('/books/ISBN/<book_type>', methods = ['GET'])
@token_required
def get_books_by_book_type(current_user_token,book_type):
    books = Book.query.filter_by(book_type = book_type).all()
    response = books_schema.dump(books)
    return jsonify(response)

@api.route('/books/ISBN/<book_ISBN>', methods = ['GET'])
@token_required
def get_books_by_ISBN(current_user_token,book_ISBN):
    books = Book.query.filter_by(ISBN = book_ISBN).all()
    response = books_schema.dump(books)
    return jsonify(response)

@api.route('/books/author_name/<book_author_name>', methods = ['GET'])
@token_required
def get_books_by_author_name(current_user_token,book_author_name):
    books = Book.query.filter_by(author_name = book_author_name).all()
    response = books_schema.dump(books)
    return jsonify(response)

@api.route('/books/book_title/<book_book_title>', methods = ['GET'])
@token_required
def get_books_by_book_title(current_user_token,book_book_title):
    books = Book.query.filter_by(book_title = book_book_title).all()
    response = books_schema.dump(books)
    return jsonify(response)

@api.route('/books/page_count/<book_page_count>', methods = ['GET'])
@token_required
def get_books_by_page_count(current_user_token,book_page_count):
    books = Book.query.filter_by(page_count = book_page_count).all()
    response = books_schema.dump(books)
    return jsonify(response)

@api.route('/books/<book_id>', methods = ['GET'])
@token_required
def get_book(current_user_token, book_id):
    fan = current_user_token.token
    if fan == current_user_token.token:
        book = Book.query.get(book_id)
        response = book_schema.dump(book)
        return jsonify(response)
    else:
        return jsonify({"message": "Valid Token Required"}),401

@api.route('/books/<book_id>', methods = ['POST','PUT'])
@token_required
def update_book(current_user_token,book_id):
    book = Book.query.get(book_id) 
    book.ISBN = request.json['ISBN']
    book.author_name = request.json['author_name']
    book.book_title = request.json['book_title']
    book.page_count = request.json['page_count']

    db.session.commit()
    response = book_schema.dump(book)
    return jsonify(response)

@api.route('/books/<book_id>', methods = ['DELETE'])
@token_required
def delete_book(current_user_token, book_id):
    book = Book.query.get(book_id)
    db.session.delete(book)
    db.session.commit()
    response = book_schema.dump(book)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET','POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            user = User(email, password = password)
            db.session.add(user)
            db.session.commit()
            flash(f'You have successfully created a user account {email}', 'User-created')
            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation. Congratulations, and welcome to the Jedi Knights', 'auth-sucess')
                return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation. Congratulations, and welcome to the Jedi Knights', 'auth-sucess')
                return redirect(url_for('site.profile'))
            else:
                flash('You have failed in your attempt to access this content', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check your Form')
    return render_template('sign_in.html', form=form)

@auth.route('/signout')
def signout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<script src="https://kit.fontawesome.com/33cbf8cef6.js" crossorigin="anonymous"></script>

<title>Library</title>
</head>
<body>
    <nav class="container-fluid navbar navbar-expand-lg navbar-dark pt-0 fixed-top" style="background-color: black;">
        <div class="container p-0 ms-5">
            <a href="{{ url_for('site.home') }}" class="navbar-brand px-5 py-0">Library</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav p-0 pt-3 ms-auto">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <p class="navbar-text" style=" color: white;">WELCOME, {{current_user.email}}!</p>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signout') }}" class="nav-link">SIGN OUT</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">PROFILE</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link">SIGN IN</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link">SIGN UP</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="#" class="nav-link">SEARCH</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">ABOUT</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">SUPPORT</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid p-0 mt-5 mb-0 mx-0">
        {% block content %}
        {% endblock %}
    </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
<footer>
    <section id="about-section">
        <div id="about-container" class="container-fluid row p-0 m-0 text-lg-start text-md-start text-sm-start text-center" style="background-color: black;">
            <div id="about-contacts" class="container-fluid col-lg-3 col-md-3 col-sm-3 col-12 p-lg-5 p-md-3 p-1">
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <p style="color: white; text-decoration: none; font-size: calc(1vw + 1vh + 1vmin); font-weight:bold">CONTACT</p>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); "><i class="fa-solid fa-map-pin"></i> ANYTOWN,LN 12345 USA</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); "><i class="fa-solid fa-envelope"></i> CONTACT@LIB.ORG</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); "><i class="fa-solid fa-phone"></i> 555-555-5555</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); "><i class="fa-solid fa-clock"></i> 5:00AM - 7:00PM</a>
                    </div>
                </div>
            </div>
            <div id="about-links" class="container-fluid col-lg-3 col-md-3 col-sm-3 col-12 p-lg-5 p-md-3 p-1">
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <p style="color: white; text-decoration: none; font-size: calc(1vw + 1vh + 1vmin); font-weight:bold">LINKS</p>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="{{ url_for('site.home') }}" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); ">HOME</a>
                    </div>
                </div>
                {% if current_user.is_authenticated %}
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="{{ url_for('auth.signout') }}" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); ">SIGN OUT</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="{{ url_for('site.profile') }}" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); ">PROFILE</a>
                    </div>
                </div>
                {% else %}
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="{{ url_for('auth.signin') }}" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); ">SIGN IN</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="{{ url_for('auth.signup') }}" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); ">SIGN UP</a>
                    </div>
                </div>
                {% endif %}
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); ">SEARCH</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); ">ABOUT</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style="color: white; text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin); ">SUPPORT</a>
                    </div>
                </div>
            </div>
            <div id="about-socials" class="container-fluid col-lg-3 col-md-3 col-sm-3 col-12 p-lg-5 p-md-3 p-1">      
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <p style="color: white; text-decoration: none; font-size: calc(1vw + 1vh + 1vmin); font-weight:bold">SOCIALS</p>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style=" text-decoration: none; color: white; font-size: calc(.5vw + .5vh + .5vmin);"><i class="fa-brands fa-facebook"></i>FACEBOOK</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style=" text-decoration: none; color: white; font-size: calc(.5vw + .5vh + .5vmin);"><i class="fa-brands fa-twitter"></i>TWITTER</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-autocol-12">
                        <a href="#" style=" text-decoration: none; color: white; font-size: calc(.5vw + .5vh + .5vmin);"><i class="fa-brands fa-youtube"></i>YOUTUBE</a>
                    </div>
                </div>
                <div class="container-fluid p-0 m-auto row">
                    <div class="container-fluid p-0 m-auto col-12">
                        <a href="#" style=" text-decoration: none; color: white; font-size: calc(.5vw + .5vh + .5vmin);"><i class="fa-brands fa-instagram"></i> INSTAGRAM</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <p class="lead text-center p-5" style="background-color: black; color: rgb(151, 151, 151); text-decoration: none; font-size: calc(.5vw + .5vh + .5vmin);">&copy; 2023 DAKOTA HAYES</p>
</footer>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'place email here ') }}
        </fieldset>
    </div>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password here ") }}
        </fieldset>
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}
</form>